# Generated by Django 5.0.1 on 2024-01-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='아름넷코드')),
                ('biz_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호')),
                ('cust_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='업체명')),
                ('biz_owner', models.CharField(blank=True, max_length=20, null=True, verbose_name='점주명')),
                ('biz_zip_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호')),
                ('biz_state', models.CharField(blank=True, max_length=10, null=True, verbose_name='주소1')),
                ('biz_city', models.CharField(blank=True, max_length=10, null=True, verbose_name='주소2')),
                ('biz_dong', models.CharField(blank=True, max_length=20, null=True, verbose_name='주소3')),
                ('biz_addr1', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소4')),
                ('biz_addr2', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소5')),
                ('biz_addr', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소6')),
                ('biz_tel_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('biz_tel_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='휴대폰번호')),
                ('biz_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='메일')),
            ],
            options={
                'db_table': 'arm_users',
                'managed': False,
            },
        ),
    ]
